version: '3.8'

services:
  # 1. The Database
  postgres:
    image: postgres:15-alpine
    container_name: shortx_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shortx_network

  # 2. Your API (The App)
  api:
    build: .  # Build from the Dockerfile in current directory
    container_name: shortx_api
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
    networks:
      - shortx_network

volumes:
  postgres_data:

networks:
  shortx_network:
    driver: bridge